const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const BOARDS=[
{name:'YC Work at a Startup',abbr:'Y',url:'https://www.workatastartup.com/jobs',desc:'High-signal startup roles with direct access to funded founders and operators.',tags:['startup','ai'],rank:1},
{name:'Wellfound',abbr:'W:',url:'https://wellfound.com/jobs',desc:'Startup jobs with strong filtering and salary / equity transparency.',tags:['startup','ai','fintech'],rank:2},
{name:'LinkedIn Jobs',abbr:'in',url:'https://www.linkedin.com/jobs/',desc:'Best for breadth, recruiter visibility, alerts, and warm-network discovery.',tags:['nyc','boston','fintech','ai'],rank:3},
{name:'Built In NYC',abbr:'b',url:'https://www.builtinnyc.com/jobs',desc:'Strong New York tech, startup, product, and GTM hiring.',tags:['nyc','startup'],rank:4},
{name:'a16z Portfolio Jobs',abbr:'a16z',url:'https://portfoliojobs.a16z.com/our-jobs',desc:'Roles across Andreessen Horowitz-backed startups and scaleups.',tags:['vc','startup','ai','fintech'],rank:5},
{name:'Sequoia Capital Jobs',abbr:'S',url:'https://jobs.sequoiacap.com/',desc:'Portfolio hiring across one of the most selective venture ecosystems.',tags:['vc','startup','ai','fintech'],rank:6},
{name:'The Ladders',abbr:'L',url:'https://www.theladders.com/jobs/search',desc:'Higher-paying roles and a broader net for senior product and business profiles.',tags:['nyc','boston'],rank:7},
{name:'VentureFizz',abbr:'vf',url:'https://venturefizz.com/jobs',desc:'Excellent Boston and NYC startup ecosystem source for product and tech roles.',tags:['boston','nyc','startup'],rank:8},
{name:'Startup Boston',abbr:'SB',url:'https://startupbos.org/',desc:'Boston startup ecosystem, community, events, and company discovery.',tags:['boston','startup'],rank:9},
{name:'Index Ventures Jobs',abbr:'I',url:'https://www.indexventures.com/startup-jobs',desc:'Portfolio hiring across Index-backed startups, with strong role and location filters.',tags:['vc','startup','ai','fintech'],rank:10},
{name:'Accel Jobs',abbr:'A',url:'https://jobs.accel.com/jobs',desc:'Large portfolio job board spanning Accel-backed technology companies.',tags:['vc','startup','ai','fintech'],rank:11},
{name:'Underdog.io',abbr:'U',url:'https://underdog.io/',desc:'Curated startup hiring marketplace with a more selective matching model.',tags:['startup','nyc'],rank:12},
{name:'Welcome to the Jungle',abbr:'WJ',url:'https://www.welcometothejungle.com/en',desc:'Modern job discovery with richer company pages and startup filtering.',tags:['startup','nyc'],rank:13},
{name:'AI Jobs',abbr:'AI',url:'https://aijobs.net/',desc:'Niche AI-focused board for product, model, engineering, GTM, and operations roles.',tags:['ai','startup'],rank:14},
{name:'eFinancialCareers',abbr:'eF',url:'https://www.efinancialcareers.com/',desc:'Useful supplement for finance-adjacent product, markets, and fintech roles.',tags:['fintech','nyc'],rank:15},
{name:'Jobland AI',abbr:'J',url:'https://www.google.com/search?q=Jobland+AI+jobs',desc:'AI-assisted job discovery and matching; useful as a supplemental source.',tags:['ai','startup'],rank:16},
{name:'TopStartups.io',abbr:'TS',url:'https://topstartups.io/jobs/',desc:'Startup-only job discovery with useful filters for stage, market, and location.',tags:['startup','ai','fintech'],rank:17},
{name:'Startup.jobs',abbr:'↗',url:'https://startup.jobs/',desc:'Broad startup roles by city, function, and remote status.',tags:['startup','nyc','boston'],rank:18}
];
const STAGES=['Saved','Applied','Recruiter Screen','Interview','Final','Offer','Closed'];
let goal=Number(localStorage.getItem('jso-goal')||8), apps=JSON.parse(localStorage.getItem('jso-apps')||'[]'), editId=null;
function save(){localStorage.setItem('jso-apps',JSON.stringify(apps));renderAll()}
function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===name+'View'));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===name));scrollTo({top:0,behavior:'smooth'});if(name==='analytics')renderAnalytics()}
$$('.nav').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>switchView(b.dataset.jump));
function boardCard(b){return `<a class="board-card spotlight-card" href="${b.url}" target="_blank" rel="noreferrer" data-tags="${b.tags.join(' ')}"><div class="board-logo">${b.abbr}</div><h3>${b.name}</h3><p>${b.desc}</p><div class="board-tags">${b.tags.slice(0,3).map(t=>`<span>${t.toUpperCase()}</span>`).join('')}</div></a>`}
function renderBoards(filter='all',q=''){const hits=BOARDS.filter(b=>(filter==='all'||b.tags.includes(filter))&&(!q||(`${b.name} ${b.desc} ${b.tags.join(' ')}`).toLowerCase().includes(q.toLowerCase())));$('#boardGrid').innerHTML=hits.map(boardCard).join('');bindSpotlights();}
$('#featuredBoards').innerHTML=BOARDS.slice(0,4).map(boardCard).join('');renderBoards();
$$('#boardFilters button').forEach(b=>b.onclick=()=>{$$('#boardFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderBoards(b.dataset.filter,$('#boardSearch').value)});$('#boardSearch').oninput=e=>{const f=$('#boardFilters .active').dataset.filter;renderBoards(f,e.target.value)};
function stageCount(s){return apps.filter(a=>a.stage===s).length}function isoToday(){return new Date().toISOString().slice(0,10)}function dateLabel(d){if(!d)return'—';const dt=new Date(d+'T12:00:00');return dt.toLocaleDateString(undefined,{month:'short',day:'numeric'})}function isDue(d){return d&&d<=isoToday()}
function renderDashboard(){const active=apps.filter(a=>!['Closed','Offer'].includes(a.stage)).length;const interviews=apps.filter(a=>['Recruiter Screen','Interview','Final'].includes(a.stage)).length;const responses=apps.filter(a=>!['Saved','Applied'].includes(a.stage)).length;const applied=apps.filter(a=>a.stage!=='Saved').length;const due=apps.filter(a=>isDue(a.nextDate)&&!['Closed','Offer'].includes(a.stage)).length;$('#statActive').textContent=active;$('#statInterviews').textContent=interviews;$('#statResponse').textContent=applied?Math.round(responses/applied*100)+'%':'—';$('#statDue').textContent=due;
 const now=new Date();$('#todayLabel').textContent=now.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'}).toUpperCase();
 const monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()+6)%7));monday.setHours(0,0,0,0);const weekly=apps.filter(a=>a.appliedDate&&new Date(a.appliedDate+'T12:00:00')>=monday).length;$('#goalCount').textContent=`${weekly} / ${goal}`;const pct=Math.min(100,Math.round(weekly/goal*100));$('#goalPct').textContent=pct+'%';$('#goalCircle').style.strokeDashoffset=314-(314*pct/100);$$('[data-goal]').forEach(b=>b.classList.toggle('active',+b.dataset.goal===goal));
 const queue=apps.filter(a=>a.nextDate&&!['Closed','Offer'].includes(a.stage)).sort((a,b)=>a.nextDate.localeCompare(b.nextDate)).slice(0,5);$('#actionQueue').innerHTML=queue.length?queue.map(a=>`<div class="action-item"><div class="action-status">${isDue(a.nextDate)?'!':'→'}</div><div><b>${a.company} · ${a.role}</b><span>${a.notes||'Next step'} · ${a.stage}</span></div><time class="${isDue(a.nextDate)?'due':''}">${dateLabel(a.nextDate)}</time></div>`).join(''):'<div class="empty-small">No next actions yet. Add an application with a follow-up date.</div>';}
$$('[data-goal]').forEach(b=>b.onclick=()=>{goal=+b.dataset.goal;localStorage.setItem('jso-goal',goal);renderDashboard()});
function renderPipeline(){const counts=STAGES.map(s=>({s,n:stageCount(s)}));$('#pipelineSummary').innerHTML=counts.map(x=>`<div class="pipe-stat"><span>${x.s}</span><strong>${x.n}</strong></div>`).join('')}
function appRow(a){return `<tr><td><strong>${a.company}</strong><small>${a.role}</small></td><td><span class="stage-pill">${a.stage}</span></td><td>${a.location||'—'}</td><td>${a.comp||'—'}</td><td>${a.source||'—'}</td><td class="${isDue(a.nextDate)?'due':''}">${a.nextDate?dateLabel(a.nextDate):'—'}<small>${a.notes?escapeHtml(a.notes).slice(0,62):''}</small></td><td><button class="row-action" data-edit="${a.id}">Edit</button></td></tr>`}
function renderTable(){const q=$('#appSearch')?.value.toLowerCase()||'',sf=$('#stageFilter')?.value||'all';const filtered=apps.filter(a=>(sf==='all'||a.stage===sf)&&(!q||(`${a.company} ${a.role} ${a.location} ${a.source}`).toLowerCase().includes(q)));$('#appTable').innerHTML=filtered.map(appRow).join('');$('#emptyApps').classList.toggle('show',filtered.length===0);$$('[data-edit]').forEach(b=>b.onclick=()=>openApp(apps.find(a=>a.id===b.dataset.edit)))}
$('#appSearch').oninput=renderTable;$('#stageFilter').onchange=renderTable;
function openApp(a=null){editId=a?.id||null;$('#modalTitle').textContent=a?'Edit opportunity':'Add opportunity';$('#deleteAppBtn').style.visibility=a?'visible':'hidden';$('#editId').value=editId||'';['company','role','stage','location','comp','source','appliedDate','nextDate','jobUrl','notes'].forEach(k=>{$('#'+k).value=a?.[k]||((k==='stage')?'Applied':'')});if(!a)$('#appliedDate').value=isoToday();$('#appDialog').showModal()}
$('#addAppBtn').onclick=()=>openApp();$('#addAppBtn2').onclick=()=>openApp();$('#closeAppDialog').onclick=()=>$('#appDialog').close();$('#appForm').onsubmit=e=>{e.preventDefault();const obj={id:editId||crypto.randomUUID(),company:$('#company').value.trim(),role:$('#role').value.trim(),stage:$('#stage').value,location:$('#location').value.trim(),comp:$('#comp').value.trim(),source:$('#source').value.trim(),appliedDate:$('#appliedDate').value,nextDate:$('#nextDate').value,jobUrl:$('#jobUrl').value.trim(),notes:$('#notes').value.trim()};if(editId)apps=apps.map(x=>x.id===editId?obj:x);else apps.unshift(obj);$('#appDialog').close();save()};$('#deleteAppBtn').onclick=()=>{if(editId&&confirm('Delete this opportunity?')){apps=apps.filter(x=>x.id!==editId);$('#appDialog').close();save()}};
$('#loadDemoData').onclick=()=>{apps=[{id:crypto.randomUUID(),company:'Northstar AI',role:'Senior Product Manager, Agents',stage:'Interview',location:'New York, NY',comp:'$210k–$250k + equity',source:'a16z',appliedDate:daysAgo(8),nextDate:daysFrom(1),jobUrl:'',notes:'Prepare agent evaluation and product sense examples.'},{id:crypto.randomUUID(),company:'LedgerWorks',role:'Product Lead, Fintech Infrastructure',stage:'Recruiter Screen',location:'Remote / NYC',comp:'$200k–$240k',source:'Referral',appliedDate:daysAgo(4),nextDate:isoToday(),jobUrl:'',notes:'Send portfolio and confirm availability.'},{id:crypto.randomUUID(),company:'ModelOps',role:'Product Manager, Enterprise AI',stage:'Applied',location:'New York, NY',comp:'$190k–$230k',source:'Wellfound',appliedDate:daysAgo(2),nextDate:daysFrom(5),jobUrl:'',notes:'Follow up if no response.'},{id:crypto.randomUUID(),company:'RiskLayer',role:'Senior PM, Financial Systems',stage:'Final',location:'Boston / Hybrid',comp:'$220k–$260k',source:'Recruiter',appliedDate:daysAgo(18),nextDate:daysFrom(2),jobUrl:'',notes:'Final panel: strategy, architecture, leadership.'}];save()}
function daysAgo(n){const d=new Date();d.setDate(d.getDate()-n);return d.toISOString().slice(0,10)}function daysFrom(n){const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function renderAnalytics(){const max=Math.max(1,...STAGES.map(stageCount));$('#funnelChart').innerHTML=STAGES.map(s=>`<div class="funnel-row"><span>${s}</span><i><b style="width:${stageCount(s)/max*100}%"></b></i><em>${stageCount(s)}</em></div>`).join('');const src={};apps.forEach(a=>{const k=a.source||'Other';src[k]=(src[k]||0)+1});const entries=Object.entries(src).sort((a,b)=>b[1]-a[1]).slice(0,5);const colors=['#8edcea','#9b94ff','#78d6b1','#d6a7f0','#627998'];let acc=0,parts=entries.map(([,n],i)=>{const start=acc/apps.length*100;acc+=n;const end=acc/apps.length*100;return `${colors[i]} ${start}% ${end}%`});$('#sourceDonut').style.background=apps.length?`conic-gradient(${parts.join(',')})`:'#121d2d';$('#donutTotal').textContent=apps.length;$('#sourceLegend').innerHTML=entries.map(([s,n],i)=>`<div><span><i style="background:${colors[i]}"></i>${s}</span><b>${n}</b></div>`).join('');const weeks=[];for(let i=7;i>=0;i--){const end=new Date();end.setDate(end.getDate()-i*7);const start=new Date(end);start.setDate(end.getDate()-6);const n=apps.filter(a=>{if(!a.appliedDate)return false;const d=new Date(a.appliedDate+'T12:00:00');return d>=start&&d<=end}).length;weeks.push({label:end.toLocaleDateString(undefined,{month:'short',day:'numeric'}),n})}const wm=Math.max(1,...weeks.map(w=>w.n));$('#weeklyBars').innerHTML=weeks.map(w=>`<div class="week-bar" style="height:${Math.max(4,w.n/wm*100)}%"><b>${w.n}</b><span>${w.label}</span></div>`).join('')}
function renderAll(){renderDashboard();renderPipeline();renderTable();renderAnalytics()}
$('#exportDataBtn').onclick=()=>{const blob=new Blob([JSON.stringify(apps,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='job-search-os-data.json';a.click();URL.revokeObjectURL(a.href)};$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(Array.isArray(data)){apps=data;save()}}catch{alert('Could not import that JSON file.')}};$('#clearData').onclick=()=>{if(confirm('Reset all locally stored application data?')){apps=[];save()}};
function commands(q=''){const items=[...['dashboard','boards','tracker','analytics'].map(v=>({label:'Go to '+v[0].toUpperCase()+v.slice(1),sub:'View',run:()=>switchView(v)})),{label:'Add application',sub:'Action',run:()=>openApp()},...BOARDS.map(b=>({label:b.name,sub:'Open board',run:()=>window.open(b.url,'_blank')}))];return items.filter(i=>i.label.toLowerCase().includes(q.toLowerCase())).slice(0,10)}function renderCommands(){const arr=commands($('#commandInput').value);$('#commandResults').innerHTML=arr.map((i,n)=>`<div class="command-item" data-command="${n}"><span>${i.label}</span><small>${i.sub}</small></div>`).join('');$$('[data-command]').forEach(el=>el.onclick=()=>{arr[+el.dataset.command].run();$('#commandDialog').close()})}function openCommand(){$('#commandDialog').showModal();$('#commandInput').value='';renderCommands();setTimeout(()=>$('#commandInput').focus(),20)}$('#searchShortcut').onclick=openCommand;$('#closeCommand').onclick=()=>$('#commandDialog').close();$('#commandInput').oninput=renderCommands;document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand()}if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();switchView('boards');setTimeout(()=>$('#boardSearch').focus(),20)}});
function bindSpotlights(){$$('.spotlight-card').forEach(c=>{if(c.dataset.bound)return;c.dataset.bound=1;c.addEventListener('mousemove',e=>{const r=c.getBoundingClientRect();c.style.setProperty('--mx',(e.clientX-r.left)+'px');c.style.setProperty('--my',(e.clientY-r.top)+'px')})})}document.addEventListener('mousemove',e=>{const g=$('.cursor-glow');g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'});const io=new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle('visible',e.isIntersecting)),{threshold:.08});$$('.reveal').forEach(x=>io.observe(x));function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
bindSpotlights();renderAll();
